### ISSUE TITLE
[BUG] Error while requiring module nuxt/cron

### ISSUE THREAD

**Issue by ReWWeR** [hywax/nuxt-cron#67]
### Version

0.6.0 Nuxt 4

### Describe the problem

Was trying to install it for the first time, but got this error message when trying to run nuxt:

```Error while requiring module nuxt/cron: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cron' is not defined by "exports" in *****/node_modules/nuxt/package.json```

### Additional info

Nuxt version with future Nuxt 4 support

**Comment by hywax-assistant** [comment]
👋 @ReWWeR
Thanks for opening your first issue here!
To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://nuxt-cron.hywax.space/community/contributing.html).

 If you like this project, please ⭐ star our repo.

**Comment by ReWWeR** [comment]
Sorry, provided wrong module name in nuxt.config file
