### ISSUE TITLE
[BUG] ReferenceError: defineNitroPlugin is not defined

### ISSUE THREAD

**Issue by ReWWeR** [hywax/nuxt-cron#92]
### Version

1.7.0

### Describe the problem

I've got `ReferenceError: defineNitroPlugin is not defined` error on server side. Not sure it is a problem on some nuxt-cron updates or some nuxt updates, but previously it was working fine on server side

### Additional info

<img width="779" alt="image" src="https://github.com/user-attachments/assets/8660b419-2545-47f3-aa7d-de7e1f6cbef2">

**Comment by Qualterink** [comment]
same, please fix it

**Comment by hywax** [comment]
Hello everyone, I didn’t have time for this before, but now the issue should be resolved in the new release.

@jbjorge thanks!
